[package]
name = "gl_app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sim_lib = { path = "../sim_lib" }
gl_lib_sdl = { path = "../../rust-gl-lib-sdl" }
failure = "0.1"